### ISSUE TITLE
Mimic objects lost type

### ISSUE THREAD

**Issue by pmareke** [davidvilla/python-doublex#24] opened 2022-04-18 07:35 UTC
Hi David! First of all thanks and congratulations for this excellent library, I use it everyday at work and it's just awesome!

I realised that when you use `Mimic`, the type of the object is lost and the Stub/Spy/Mock becames `Any`

![image](https://user-images.githubusercontent.com/3502075/163773218-11397e85-1f52-4e50-b357-a301fab82604.png)

![image](https://user-images.githubusercontent.com/3502075/163773371-7a2a8ac1-bf3e-4eaf-bfa1-3c0406ac979f.png)

Am I doing something wrong?

Thanks!

**Comment by pmareke** [comment] 2022-04-18 08:17
Duplicate it sorry.

https://github.com/davidvilla/python-doublex/issues/23

**Comment by davidparsson** [comment] 2022-04-18 18:12
Hi, and thanks!

Proper type hints are not yet implemented in this library as there are some technical obstacles. I would like to see that done but I’m not sure how. Until then, editors will probably do their best to infer types, each in its own way, and I’m not surprised they don’t get it right. I’m only guessing now, but proper type hints is probably the only solution here.

Hence, I believe that this is a duplicate of #18.

**Comment by davidparsson** [comment] 2022-04-18 18:13
Please reopen if you don’t agree, or if any new information comes up.

**Closed as completed by davidparsson** 2022-04-18 18:13 UTC

**Comment by pmareke** [comment] 2022-04-19 05:48
Thanks David!

Close is fine don't worry (I wasn't sure if this issue will duplicate #18), thanks anyway!
